name: Release
on:
  release:
    types: [published]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'taskmedia/helm_test'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        run: |
          curl -L https://git.io/get_helm.sh | bash -s -- -v v3.7.1

      - name: Create release binary
        run: |
          helm package ./ --destination release/

      - name: Update Index
        env:
          PROJECT: github.com/taskmedia/helm_ipsec-vpn-server
          REPO_URL: https://helm.task.media/ipsec-vpn-server
        run: |
          rm -rf ./gh-pages.zip
          curl -sSLO https://${PROJECT}/archive/gh-pages.zip
          unzip -oj ./gh-pages.zip -d ./repo/
          cp ./release/*tgz ./repo/
          cp ./README.md ./repo/index.md
          helm repo index --merge ./repo/index.yaml --url ${REPO_URL} ./repo

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          repository-name: taskmedia/helm
          branch: gh-pages
          # problem was org-secrets only available on public 
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          folder: repo
          clean: false
